### PR TITLE
add ability to pass component to final-field, handle reInitialValues

### PR DESCRIPTION
**Pull request by alirezavalizade**
- add feature for using generic components instead of html and slot-scope
- handle reInitialValues

### CODE REVIEW

**Comment by alirezavalizade** [comment]
ping @egoist

**Comment by alirezavalizade** [comment]
@egoist

**Comment by Seminioni** [comment]
@egoist what are your minds about this PR? 

Btw are planning to maintain vue-final-form?

**Comment by alirezavalizade** [comment]
https://github.com/ikbenfrits/final-form-vue

**Comment by Seminioni** [comment]
@alirezavalizade why did you close it?

**Pull request closed without merging**
