### PR TITLE
feat: Upgrade to vue 3

### PR DESCRIPTION
**Pull request by apetrenkov**
Hello!

While Vue 3 is coming, I've decided to upgrade this library.

There are a few changes besides upgrading the core dependencies:
- `poi`, as it doesn't support vue 3, was replaced with blazingly fast `vite` (and it's even faster than `poi`);
- `nano-assign` was removed because browsers that support vue 3 also support `Object.assign`;
- development packages were also upgraded.

It also looks like the code doesn't fit modern eslint rules, so I can make all relevant changes in a new commit.

### CODE REVIEW

**Comment by egoist** [comment]
Would be nice if you can update it to use composition API

**Comment by artptr** [comment]
I've got it that way to be the easiest to use in a real app I think.

For legacy components the API doesn't changed, but for composition API I decided to leave returned `final-form` objects mostly as is:
- `useForm` returns separate `finalForm` (with the `handleSubmit` helper) and `formState` objects;
- `useField` just extends original `fieldState` object with `events` handlers object (I couldn't find the way to extract the `meta` object to redesign the `fieldState` as for legacy components);

Also according to the [Composition API behavior](https://github.com/vuejs/vue-next/issues/4813) it's impossible (using public API) to inject provided `finalForm` object from the same component, so autoinjection will work only for legacy components, and we must pass `finalForm` manually to each `useField` function.

Please check the design of the solution and share your thoughts about it.

**Comment by egoist** [comment]
> Also according to the Composition API behavior it's impossible (using public API) to inject provided finalForm object from the same component, so autoinjection will work only for legacy components, and we must pass finalForm manually to each useField function.

`useField` should only be used in a child component, see react-final-form and formik, so it's ok to just inject the `form`, an error should be thrown if no form was found

**Comment by artptr** [comment]
Ok, I see. Also do we need to change the behavior of the `useForm` like in react-final-form or Formik? I.e. should `useForm` be only injector for the form object created by the `<FinalForm>` tag, or it should create the form object itself and provide it to other components as it's implemented now?

**Comment by egoist** [comment]
> or it should create the form object itself and provide it to other components as it's implemented now?

this, since we should be able to use `useForm` without the `Form` component

**Comment by artptr** [comment]
So that's exactly the behavior we have now, but I think that additional ability to inject the form object manually could be useful if we want to declare a form in a single component through `setup` section like in the `Composition` example.

Also we may want to get a form object from children components. In react-final-form and formik that ability is provided by `useForm` hook. So do we need to have something like `useCurrentForm` because our `useForm`creates a new form?

**Comment by egoist** [comment]
`useCurrentForm` sounds like a nice addtion

**Comment by artptr** [comment]
Hey! Any news since my last commit?

**Pull request merged**
